### ISSUE TITLE
Using music disc-music as Menu Music

### ISSUE THREAD

**Issue by BrekiTomasson** [LudoCrypt/Vistas#3]
Hey! Trying to work out how to use music from one of the music discs as menu music, and can't figure out the format to use - especially considering Minecraft's Sound Event naming doesn't seem to be very consistent. I'm trying to add the Pigstep track to my Vistas menu, and I've tried setting "musicId" to: `music_disc.pigstep`, `music.music_disc.pigstep`, `music.disc.pigstep`, all to no success. Any ideas?

**Comment by LudoCrypt** [comment]
music_disc.pigstep should be the correct one to use, if you're not hearing pigstep, it might be because other music is playing, such as menu music, or the time for the music to play hasn't been reached yet! Try using a musicSound instead of a musicId. Details on how are in the [wiki documentation.](https://github.com/TerraformersMC/Vistas/wiki/Documentation)
